export function exportToCSV(data: any[], filename: string) {
  if (!data || data.length === 0) {
    console.warn("No data to export");
    return;
  }

  const headers = Object.keys(data[0]);
  const csvContent = [
    headers.join(","),
    ...data.map((row) =>
      headers
        .map((header) => {
          const value = row[header];
          if (typeof value === "string" && value.includes(",")) {
            return `"${value}"`;
          }
          return value ?? "";
        })
        .join(",")
    ),
  ].join("\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);

  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}-${new Date().toISOString().split("T")[0]}.csv`);
  link.style.visibility = "hidden";

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function exportToJSON(data: any[], filename: string) {
  const jsonString = JSON.stringify(data, null, 2);
  const blob = new Blob([jsonString], { type: "application/json;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);

  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}-${new Date().toISOString().split("T")[0]}.json`);
  link.style.visibility = "hidden";

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function generateBranchReport(branchData: any, branchName: string): string {
  const timestamp = new Date().toLocaleString();
  const report = `
BRANCH MANAGEMENT REPORT
Branch: ${branchName}
Generated: ${timestamp}

================== SUMMARY ==================
Total Loans: ${branchData.totalLoans || 0}
Active Loans: ${branchData.activeLoans || 0}
Pending Loans: ${branchData.pendingLoans || 0}
Total Members: ${branchData.totalMembers || 0}
Total Savings: KES ${branchData.totalSavings?.toLocaleString() || 0}
Collection Rate: ${branchData.collectionRate?.toFixed(1) || 0}%

================== STAFF ==================
${branchData.staffCount || 0} staff members

${
  branchData.staffByRole
    ? Object.entries(branchData.staffByRole)
        .map(([role, count]) => `${role}: ${count}`)
        .join("\n")
    : "No staff information"
}

================== GROUPS ==================
Total Groups: ${branchData.groupCount || 0}

${
  branchData.groups
    ? branchData.groups
        .map(
          (group: any) => `
Group: ${group.name}
Members: ${group.totalMembers}
Savings: KES ${parseFloat(group.totalSavings || 0).toLocaleString()}
Outstanding Loans: KES ${parseFloat(group.totalLoansOutstanding || 0).toLocaleString()}
Repayment Rate: ${group.repaymentRate?.toFixed(1) || 0}%
`
        )
        .join("\n")
    : "No group information"
}

================== LOAN PRODUCTS ==================
Total Products: ${branchData.products?.length || 0}

${
  branchData.products
    ? branchData.products
        .map(
          (product: any) => `
Product: ${product.name}
Price: KES ${parseFloat(product.sellingPrice || 0).toLocaleString()}
Stock: ${product.stockQuantity || 0}
Category: ${product.categoryId || "Unknown"}
`
        )
        .join("\n")
    : "No product information"
}

================== STORE & SUPPLIERS ==================
Total Suppliers: ${branchData.suppliers?.length || 0}

${
  branchData.suppliers
    ? branchData.suppliers
        .map(
          (supplier: any) => `
Supplier: ${supplier.name}
Contact: ${supplier.phone}
Email: ${supplier.email || "N/A"}
Location: ${supplier.location || "N/A"}
Rating: ${supplier.rating || "N/A"}
Active: ${supplier.isActive ? "Yes" : "No"}
`
        )
        .join("\n")
    : "No supplier information"
}

Generated by Imarisha Loan Management System
`;

  return report;
}

export function downloadReport(content: string, filename: string) {
  const blob = new Blob([content], { type: "text/plain;charset=utf-8;" });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);

  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}-${new Date().toISOString().split("T")[0]}.txt`);
  link.style.visibility = "hidden";

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

export function flattenGroupData(groups: any[]): any[] {
  return groups.map((group: any) => ({
    "Group Name": group.name,
    "Total Members": group.totalMembers || 0,
    "Total Savings (KES)": parseFloat(group.totalSavings || 0).toLocaleString(),
    "Outstanding Loans (KES)": parseFloat(group.totalLoansOutstanding || 0).toLocaleString(),
    "Repayment Rate (%)": (group.repaymentRate || 0).toFixed(1),
    "Location": group.location || "N/A",
  }));
}

export function flattenStaffData(staff: any[]): any[] {
  return staff.map((user: any) => ({
    "Full Name": `${user.firstName} ${user.lastName}`,
    "Username": user.username,
    "Email": user.email || "N/A",
    "Phone": user.phone || "N/A",
    "Role": user.role?.replace(/_/g, " ") || "N/A",
    "Status": user.isActive ? "Active" : "Inactive",
  }));
}

export function flattenProductData(products: any[]): any[] {
  return products.map((product: any) => ({
    "Product Name": product.name,
    "Category": product.categoryId || "N/A",
    "Buying Price (KES)": parseFloat(product.buyingPrice || 0).toLocaleString(),
    "Selling Price (KES)": parseFloat(product.sellingPrice || 0).toLocaleString(),
    "Stock Quantity": product.stockQuantity || 0,
    "Low Stock Threshold": product.lowStockThreshold || 0,
    "Status": product.is_active ? "Active" : "Inactive",
  }));
}

export function flattenSupplierData(suppliers: any[]): any[] {
  return suppliers.map((supplier: any) => ({
    "Supplier Name": supplier.name,
    "Company": supplier.companyName || "N/A",
    "Contact Person": supplier.contactPerson || "N/A",
    "Phone": supplier.phone,
    "Email": supplier.email || "N/A",
    "Location": supplier.location || "N/A",
    "Rating": supplier.rating || "N/A",
    "Total Supplies": supplier.totalSupplies || 0,
    "Status": supplier.isActive ? "Active" : "Inactive",
  }));
}

export function flattenLoanData(loans: any[]): any[] {
  return loans.map((loan: any) => ({
    "Loan ID": loan.id || "N/A",
    "Member": loan.memberName || "N/A",
    "Amount (KES)": parseFloat(loan.totalAmount || 0).toLocaleString(),
    "Status": loan.status || "N/A",
    "Applied Date": loan.appliedDate || "N/A",
    "Disbursed Date": loan.disbursedDate || "N/A",
    "Expected Due Date": loan.expectedDueDate || "N/A",
  }));
}
