"""Add system subscriptions table

Revision ID: 888e0210914f
Revises: b4c36442d5cd
Create Date: 2025-12-24 18:22:57.038059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888e0210914f'
down_revision = 'b4c36442d5cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_subscriptions')
    # ### end Alembic commands ###
