"""Sync models with schema

Revision ID: 8f1a7a7315b5
Revises: d4e5f6g7h8i9
Create Date: 2025-12-19 16:41:13.662773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1a7a7315b5'
down_revision = 'd4e5f6g7h8i9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('company_name', sa.Text(), nullable=True),
    sa.Column('contact_person', sa.Text(), nullable=True),
    sa.Column('bank_name', sa.Text(), nullable=True),
    sa.Column('bank_account', sa.Text(), nullable=True),
    sa.Column('mpesa_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('total_supplies', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('biometric_auths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('auth_type', sa.Text(), nullable=False),
    sa.Column('biometric_template', sa.Text(), nullable=True),
    sa.Column('device_id', sa.Text(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('branch_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('stock_quantity', sa.Integer(), nullable=False),
    sa.Column('low_stock_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['loan_products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_officer_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Text(), nullable=False),
    sa.Column('visits_completed', sa.Integer(), nullable=True),
    sa.Column('applications_created', sa.Integer(), nullable=True),
    sa.Column('applications_submitted', sa.Integer(), nullable=True),
    sa.Column('approval_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('photos_captured', sa.Integer(), nullable=True),
    sa.Column('avg_visit_duration', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('member_feedback_score', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('movement_type', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_number', sa.Text(), nullable=True),
    sa.Column('processed_by', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['loan_products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('supplier_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('minimum_order', sa.Integer(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['loan_products.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sync_queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('operation', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_officer_visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Numeric(precision=10, scale=8), nullable=False),
    sa.Column('longitude', sa.Numeric(precision=11, scale=8), nullable=False),
    sa.Column('visit_purpose', sa.Text(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photos_count', sa.Integer(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mobile_loan_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('loan_type_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('application_status', sa.Text(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('form_data', sa.JSON(), nullable=True),
    sa.Column('visited_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['loan_type_id'], ['loan_types.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('photo_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('related_entity_type', sa.Text(), nullable=False),
    sa.Column('related_entity_id', sa.Integer(), nullable=False),
    sa.Column('photo_url', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('gps_latitude', sa.Numeric(precision=10, scale=8), nullable=True),
    sa.Column('gps_longitude', sa.Numeric(precision=11, scale=8), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.DateTime(), nullable=False),
    sa.Column('location_lat', sa.Float(), nullable=True),
    sa.Column('location_lng', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('uq_achievements_name', ['name'])
        batch_op.drop_column('category')
        batch_op.drop_column('icon')

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon_url', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.create_unique_constraint('uq_badges_name', ['name'])
        batch_op.drop_column('icon')

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.alter_column('reward_points',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'active'"))

    with op.batch_alter_table('leaderboards', schema=None) as batch_op:
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)
        # batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('branch_id')
        batch_op.drop_column('score')

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_type', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('discount_percentage', sa.Numeric(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('max_redemptions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('redeemed_count', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.alter_column('points_required',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('type')
        batch_op.drop_column('value')

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.drop_column('unlocked_at')

    with op.batch_alter_table('user_challenges', schema=None) as batch_op:
        batch_op.alter_column('progress',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'"))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'ongoing'"))

    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.create_unique_constraint('uq_user_points_user_id', ['user_id'])

    with op.batch_alter_table('user_rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('earned_at', sa.DateTime(), nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'available'"))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_users_role_id_roles', 'roles', ['role_id'], ['id'])
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.TEXT(), nullable=False))
        batch_op.drop_constraint('fk_users_role_id_roles', type_='foreignkey')
        batch_op.drop_column('role_id')

    with op.batch_alter_table('user_rewards', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'available'"))
        batch_op.drop_column('earned_at')

    with op.batch_alter_table('user_points', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_points_user_id', type_='unique')
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('user_challenges', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'ongoing'"))
        batch_op.alter_column('progress',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))

    with op.batch_alter_table('user_achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlocked_at', sa.DATETIME(), nullable=False))

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('value', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.TEXT(), server_default=sa.text("'available'"), nullable=True))
        batch_op.alter_column('points_required',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('is_active')
        batch_op.drop_column('redeemed_count')
        batch_op.drop_column('max_redemptions')
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('reward_type')

    with op.batch_alter_table('leaderboards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('branch_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), nullable=True))
        batch_op.create_foreign_key(None, 'branches', ['branch_id'], ['id'])
        batch_op.alter_column('last_updated',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('rank',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('challenges', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'active'"))
        batch_op.alter_column('end_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('reward_points',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('is_active')
        batch_op.drop_column('category')
        batch_op.drop_column('icon_url')

    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.TEXT(), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('points')
        batch_op.drop_column('icon_url')

    op.drop_table('visits')
    op.drop_table('photo_documents')
    op.drop_table('mobile_loan_applications')
    op.drop_table('field_officer_visits')
    op.drop_table('sync_queues')
    op.drop_table('supplier_products')
    op.drop_table('stock_movements')
    op.drop_table('field_officer_performance')
    op.drop_table('branch_products')
    op.drop_table('biometric_auths')
    op.drop_table('role_permissions')
    op.drop_table('suppliers')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
